### PR TITLE
Support explicit coarse- and fine-grained allocations

### PR DESCRIPTION
**Pull request by mcfadden8**
With HIP devices, we have the ability to influence how coherency of memory that is shared between devices and host processors.

This PR introduces a new `GranularityController` strategy that may be used to specify a cohrerency mode that an alloocator will produce.  Two options are currently offered, `FineGrainedCoherence` and `CoarseGrainedCoherence`.  The former means that coherency will be maintained and the latter is not guarunteed to be maintained until after a synchronization operation has been done with the using device.

### CODE REVIEW

**Comment by mcfadden8** [comment]
@davidbeckingsale, I am done with my changes to support this feature and I think this is ready for review.  At this point, I believe that this should be ready (or close to ready) to merge.

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale, I am done with my changes to support this feature and I think this is ready for review. At this point, I believe that this should be ready (or close to ready) to merge.

Can you address the CI failures?

**Comment by davidbeckingsale** [comment]
CC @adayton1 @MrBurmark

**Review by kab163 — APPROVED** [review]
We should make an issue to add official documentation for this

**Comment by rhornung67** [comment]
> We should make an issue to add official documentation for this

You could just sprinkle `// document this` liberally throughout the code.... 😄

**Pull request merged**
