### PR TITLE
Add Spack environment files for local development

### PR DESCRIPTION
**Pull request by davidbeckingsale**
```
spack env activate .spack_env/llnl
spack install umpire@develop
```

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by adrienbernede** [comment]
@davidbeckingsale I understand the intent of this PR, although it appears to me as concurrent to #481 which is waiting for review. (I did not mark it as ready for review though...).

Note that using the `compilers.yaml` and `packages.yaml` as currently defined is radiuss-spack-config exposes you to mix-ups with an existing `~/.spack` configuration. To avoid that one would have to start those files with `compilers::` and `packages::` respectively.

**Comment by mcfadden8** [comment]
Is this a replace, alternative, or developer-only option to `git submodule init && git submodule update  && cmake && make`?  If so, should README.md be updated?  Also, can a recipe/workflow be described that is specific to umpire be described somewhere?  I am think the following use cases would be helpful to describe:

- Initial clone and (spack) build
- Update to file and (spack) build update
- Location of installed executables
- Stash and switch branch
- Interaction with vscode debugger (launch.json and settings.json updates)

**Review by mcfadden8 — APPROVED** [review]

**Review by kab163 — APPROVED** [review]

**Pull request merged**
