### PR TITLE
Update splicer code to use C_SIZE_T for dimension array

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
CC @aaroncblack @rchen20

**Comment by aaroncblack** [comment]
Thanks David.  Looks like its failing the NVCC test?

**Comment by rhornung67** [comment]
It looks like you are running into disk space limits on azure. We ran into this in RAJA recently. After trying several things, I could not resolve the issue, which seems to be due to the rse-ops images containing a bunch of Spack remnants that we don't need and which cause testing to blow past the space limit. I removed our GPU builds, except for SYCL, on azure which we test on LC GitLab CI anyway. @white238 tried to resolve the issue with res-ops folks, but was unable to make progress with them.

**Comment by davidbeckingsale** [comment]
Switching to different approach.

**Pull request closed without merging**
