### PR TITLE
Bugfix/um 852 gitlab ci prefix

### PR DESCRIPTION
**Pull request by kab163**

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]

**Review by davidbeckingsale — CHANGES_REQUESTED** [review]
It doesn't look like the make clean dose anything? At least according to the log...

**Comment by kab163** [comment]
I just noticed there's a "cp: cannot stat '/usr/WS1/ukbeck/gitlab-runner/builds/zkQzXxmM/0/gitlab/radiuss/Umpire/scripts/radiuss-spack-configs/mirrors.yaml': No such file or directory" warning at https://lc.llnl.gov/gitlab/radiuss/Umpire/-/jobs/192947#L88, but it still created a host config

**Comment by davidbeckingsale** [comment]
> I just noticed there's a "cp: cannot stat '/usr/WS1/ukbeck/gitlab-runner/builds/zkQzXxmM/0/gitlab/radiuss/Umpire/scripts/radiuss-spack-configs/mirrors.yaml': No such file or directory" warning at https://lc.llnl.gov/gitlab/radiuss/Umpire/-/jobs/192947#L88, but it still created a host config

We don't have that file so I don't think it's a problem. We just need the compilers and packages yaml files.

**Review by adrienbernede — COMMENTED** [review]
This looks good to me!

**Comment by kab163** [comment]
> It doesn't look like the make clean dose anything? At least according to the log...

I added something that should tell us the space used before and after the "make clean" - I think it's doing what we want

**Review by davidbeckingsale — APPROVED** [review]

**Pull request merged**
