### PR TITLE
Update BLT and add CI job for PGI + CUDA

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by mcfadden8** [comment]
Hi @davidbeckingsale, I'm assuming you are still fixing build issues on gitlab.  Just ping me when ready.

**Comment by davidbeckingsale** [comment]
> Hi @davidbeckingsale, I'm assuming you are still fixing build issues on gitlab. Just ping me when ready.

Yeah I should be able to get it working soon.

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
@mcfadden8 - this is ready, not updating CHANGELOG since it's an "internal" change.

**Comment by davidbeckingsale** [comment]
LGTM

**Pull request merged**
