### PR TITLE
Add mixed pool to allocator_benchmarks

### PR DESCRIPTION
**Pull request by jdahm**
- [x] Merge #178

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Did you fix the crashes?

**Comment by jdahm** [comment]
The mixed pool is relatively small (a few MB). In that case, I think may initializes all tests (pools) before running the tests. Filtering to only run a few tests is a workaround. There are too many benchmarks to run if you compile with CUDA.

**Comment by jdahm** [comment]
I'm checking again for the crash...

**Comment by jdahm** [comment]
This should be ready to go now

**Pull request merged**
