### PR TITLE
[Woptim] uberenv update after PR merge

### PR DESCRIPTION
**Pull request by adrienbernede**
Per https://github.com/LLNL/Umpire/pull/761#issuecomment-1180514795

Since https://github.com/LLNL/uberenv/pull/84 was merged, we update to point to a legitimate commit instead of a feature branch.

### CODE REVIEW

**Comment by adrienbernede** [comment]
Only intel 18 failing now, will wait for #767 to be merged.

**Comment by davidbeckingsale** [comment]
@adrienbernede looks like latest commit broke, was that expected?

**Comment by adrienbernede** [comment]
@davidbeckingsale it _looks like_ the previous commit passed, but GitLab did not have time to start.

The important conclusion is that the intel 18 target was removed and ruby is passing. CI is failing because of corona switch to flux. Looking at that now.

**Comment by adrienbernede** [comment]
@davidbeckingsale Good to go.

**Review by davidbeckingsale — APPROVED** [review]

**Pull request merged**
