### PR TITLE
Release/2024.07.0

### PR DESCRIPTION
**Pull request by kab163**
The Re-Release of 2024.07.0, this time including camp updates from latest release

### CODE REVIEW

**Comment by kab163** [comment]
Sorry for all the churn on this - it should be good to go now with latest camp 2024.07.0 release

**Comment by adayton1** [comment]
I'm a little confused about what is happening with this merge request. Why is it showing diffs for things that are already in develop (https://github.com/LLNL/Umpire/pull/897/files)? Are you going to delete the 2024.07.0 tag and replace it after this goes in? I'm wondering if it would be better just to do a patch release.

**Comment by kab163** [comment]
> I'm a little confused about what is happening with this merge request. Why is it showing diffs for things that are already in develop (https://github.com/LLNL/Umpire/pull/897/files)? Are you going to delete the 2024.07.0 tag and replace it after this goes in? I'm wondering if it would be better just to do a patch release.

I think I fixed that too.. Old tags and release deleted. When this is pushed it will be as if none of that other stuff happened (I hope) and then I will recreate the tag/release as 2024.07.0

**Review by rhornung67 — APPROVED** [review]
LGTM! .... and release....

**Review by adayton1 — APPROVED** [review]
LGTM

**Pull request merged**
