### PR TITLE
Spack config as a submodule

### PR DESCRIPTION
**Pull request by adrienbernede**
This pull request moves Spack configuration files used by Uberenv in a submodule.
The goal is to share those configuration files between projects, rather than duplicate them.

Spack configuration files will then be stored in https://github.com/LLNL/radiuss-spack-configs.

Linked to https://github.com/LLNL/RAJA/pull/903, https://github.com/LLNL/CHAI/pull/157.

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
@davidbeckingsale Windows tests keep failing is some cryptic way:
https://dev.azure.com/davidbeckingsale/Umpire/_build/results?buildId=4573&view=logs&j=e86dc13c-2c7f-5e0c-97c7-56ab30de067e&t=3e749a6c-2861-5adf-fed3-1271e101bdcf

Any idea?

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale Windows tests keep failing is some cryptic way:
> https://dev.azure.com/davidbeckingsale/Umpire/_build/results?buildId=4573&view=logs&j=e86dc13c-2c7f-5e0c-97c7-56ab30de067e&t=3e749a6c-2861-5adf-fed3-1271e101bdcf
> 
> Any idea?

I'm not sure what's going on. Trying some things right now 😄

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Review by davidbeckingsale — APPROVED** [review]

**Pull request merged**
