### PR TITLE
[Woptim] update local packages

### PR DESCRIPTION
**Pull request by adrienbernede**
It looks like the local and upstream Umpire Spack packages diverged about 3 years ago.

For the RAJA package update, my strategy was to take the upstream package, and get it to pass the CI.
For the Umpire one, the differences are greater. I am taking the upstream Package, adding the many variants for the local one, and some changes from the recent RAJA packages release changes (newer BLT, CMake requirements) and then I will make sure the CI passes.

List of changes:
- Most recent versions
- Turn off submodules for recent versions
- Add patches from upstream Spack packages
- Adding new variants from local package
- Changing some variant defaults: shared, tests, device_alloc -> had to update the CI specs accordingly
- Adding CMake and BLT requirements similar to RAJA -> guessed that requirements were the same
- Merge compiler and toolchain options (gcc, hip, cuda)
- Unified use of “ instead of ‘.
- Verify that the CMake options prefix is correctly set regarding Umpire versions.
- Pass list of arch to CMAKE_HIP_ARCHITECTURES
- Default to ~tools, turn it on in CI except on corona. Add conflict +tools when +rocm.

updates:
 - spack@0.18.1 -> spack@0.19.0.
 - radiuss-spack-configs updated accordingly to support new Spack syntax.
 - radiuss-shared-ci@2022.09.0 -> [radiuss-shared-ci@2022.12.0rc](mailto:radiuss-shared-ci@2022.12.0rc).

newer radiuss-shared-ci update brings:
 - support for spack@0.19.1
 - improved performance (not more project clone in status jobs)
 - improved logs (prints a complete reproducer of the current job)
 - jobs will not be triggered on a machine that is not available
 - possibility to prevent CI to run on Draft PRs.

Notes:
- Attempt to set hip as CXX compiler failed: it’s causing a CMake error which is not visible in RAJA... under investigation

Relates to:
https://github.com/LLNL/RAJA/pull/1338
https://github.com/LLNL/CHAI/pull/218

### CODE REVIEW

**Comment by adrienbernede** [comment]
@davidbeckingsale your feedback is welcome on this.
This seems ready, but I’m currently updating the CHAI package and will update the Umpire one if there are inconsistencies.
Also, it’s a good time for change requests.

**Review by davidbeckingsale — DISMISSED** [review]

**Comment by adrienbernede** [comment]
@davidbeckingsale sorry for the confusion, you’ll have to approve that one (I merged #797 in it).

**Comment by adrienbernede** [comment]
@davidbeckingsale I’m confident the CI should pass this time.

**Comment by mcfadden8** [comment]
Hi @adrienbernede,

The notes mention a hip/CXX problem that is still under investigation.  Did this get resolved?  Is it required for this ticket?

**Comment by adrienbernede** [comment]
@mcfadden8 Good point, and thank you for reading through the notes 👍🏻 .

In facts, this should not prevent the merge: The issue is that I cannot mimic exactly the way RAJA is handling the hip compiler in the RAJA package. But I feel like there is something to understand.

This is mostly a remark for you and @davidbeckingsale who will likely understand the reasons of this better than me.
- See this for the portion of code in RAJA package: 
https://github.com/LLNL/radiuss-spack-configs/blob/0c15d9b6e065f42ccc519aacec10fbdac84b58d8/packages/raja/package.py#L136
- and here for the comment left in Umpire package: 
https://github.com/LLNL/radiuss-spack-configs/blob/0c15d9b6e065f42ccc519aacec10fbdac84b58d8/packages/umpire/package.py#L191

**Review by mcfadden8 — APPROVED** [review]
Nice work @adrienbernede - I had one question, but if we decide to do anything about it, I think it should probably be done as a separate activity.

**Comment by adrienbernede** [comment]
> Nice work @adrienbernede - I had one question, but if we decide to do anything about it, I think it should probably be done as a separate activity.

Please open an issue and mention me then ;).

**Pull request merged**
