### PR TITLE
Release/5.0.0

### PR DESCRIPTION
**Pull request by kab163**
I hope I did this right...

### CODE REVIEW

**Review by mcfadden8 — APPROVED** [review]

**Comment by mcfadden8** [comment]
Thanks @kab163,

I did not have time to review all 244 files.  But as long as the recipe was followed, I am okay with this.

**Comment by kab163** [comment]
> Thanks @kab163,
> 
> I did not have time to review all 244 files. But as long as the recipe was followed, I am okay with this.

Yea haha, the "initial release modifications" commit has all the release-specific stuff - but yea I just followed the confluence recipe. (https://github.com/LLNL/Umpire/pull/499/commits/9b30e8cfae2a0cfaa06e4a3a6f0b48ea0ad29704)

**Comment by davidbeckingsale** [comment]
You can visit this url to see the release-specific changes: https://github.com/LLNL/Umpire/compare/develop...release/5.0.0

**Review by davidbeckingsale — APPROVED** [review]
👍

**Pull request merged**
