### PR TITLE
[Woptim] Shared ci 2023.10.0

### PR DESCRIPTION
**Pull request by adrienbernede**
## Summary

Update Shared CI to 2023-10-0, add poodle machine, update Spack configs accordingly.

Fine tune allocation duration.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@adrienbernede is this ready to go?

**Comment by adrienbernede** [comment]
@davidbeckingsale I think it’s been ready for quite some time. I should have pinged you.
You could merge it. #864 Will supersede it, and should be ready as soon as corona is back to prove the tests are passing.

**Comment by davidbeckingsale** [comment]
Let's just wait and merge #864 then

**Comment by adrienbernede** [comment]
Closed in favor of #864

**Pull request closed without merging**
