### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by jdahm** [comment]
Umpire is taking a large step forward with this release. Great work everyone!

**Comment by davidbeckingsale** [comment]
@mcfadden8 @jdahm - please review/approve 😄

**Comment by mcfadden8** [comment]
Let's hold off until you read the latest email concerning testing.

**Comment by jdahm** [comment]
@mcfadden8 good catch - I see that message now too. I'm trying to get a reproducer...

**Comment by davidbeckingsale** [comment]
@mcfadden8 @jdahm - this is ready for a final review/approval.

**Pull request merged**
