### PR TITLE
Initialize m_default_allocator correctly

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by gzagaris** [comment]
👍 🚀

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
@mcfadden8 - I added a test, this is ready to go.

**Comment by davidbeckingsale** [comment]
LGTM

**Review by mcfadden8 — APPROVED** [review]
Thanks @davidbeckingsale

**Pull request merged**
