### PR TITLE
nvcc compile flags for use with CUDA_RESOLVE_DEVICE_SYMBOLS 

### PR DESCRIPTION
**Pull request by PhilipDeegan**
test #637 with rdc=true

### CODE REVIEW

**Comment by PhilipDeegan** [comment]
The error is related to CMake INTERFACE link properties, which I don't see with CMake 3.21.2

but this modification was required to not have link errors later, or when building shared libaries (which seems like the best thing to do with this IMO)

I tried
```
target_compile_options(umpire PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-rdc=true>)
```

but it didn't appear to add the flag

**Comment by white238** [comment]
I'm not sure why that generator expression did not work @PhilipDeegan .  Can you try the following macro to figure out if for some reason the target properties are causing you a problem?

```
blt_print_target_properties(TARGET umpire)
```

This will print all target properties when you run cmake.

**Comment by davidbeckingsale** [comment]
Base on discussion with NVIDIA this is not the correct approach, so I'm closing this PR and #637

**Comment by PhilipDeegan** [comment]
I think I only needed to build shared libs for umpire anyway

**Pull request closed without merging**
