### PR TITLE
Set CUDA_RESOLVE_DEVICE_SYMBOLS on Umpire libraries

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by kab163** [comment]
@davidbeckingsale - Why was this never merged?

**Comment by davidbeckingsale** [comment]
It's the incorrect approach.

**Comment by kab163** [comment]
Ok, well Matt said that there was a specific line in here that solved his issue. He compiled statically with cuda, but got linker errors:
Use --sandbox_debug to see verbose messages from the sandbox
ld.lld: error: undefined symbol: __cudaRegisterLinkedBinary_5f1ad456_13_Allocator_cpp_a17095a1
>>> referenced by tmpxft_0000029c_00000000-6_Allocator.cudafe1.cpp
>>>               Allocator.cpp.o:(__sti____cudaRegisterAll()) in archive bazel-out/k8-fastbuild/bin/external/umpire/install/lib/libumpire.a

ld.lld: error: undefined symbol: __cudaRegisterLinkedBinary_26f5691f_10_Replay_cpp_5eca6429
>>> referenced by tmpxft_0000029a_00000000-6_Replay.cudafe1.cpp
>>>               Replay.cpp.o:(__sti____cudaRegisterAll()) in archive bazel-out/k8-fastbuild/bin/external/umpire/install/lib/libumpire.a

ld.lld: error: undefined symbol: __cudaRegisterLinkedBinary_10814704_19_ResourceManager_cpp_42a9a1b2
>>> referenced by tmpxft_0000029d_00000000-6_ResourceManager.cudafe1.cpp
>>>               ResourceManager.cpp.o:(__sti____cudaRegisterAll()) in archive bazel-out/k8-fastbuild/bin/external/umpire/install/lib/libumpire.a

ld.lld: error: undefined symbol: __cudaRegisterLinkedBinary_0d9bf56f_10_Umpire_cpp_4507af2f
>>> referenced by tmpxft_0000029e_00000000-6_Umpire.cudafe1.cpp
>>>               Umpire.cpp.o:(__sti____cudaRegisterAll()) in archive bazel-out/k8-

And that this line from the PR solved the problem:
`set_target_properties(umpire umpire_resource umpire_strategy umpire_op umpire_util PROPERTIES CUDA_RESOLVE_DEVICE_SYMBOLS On)`

**Comment by davidbeckingsale** [comment]
Umpire needs a device link step when using CUDA. The UMPIRE_ENABLE_DEVICE_ALLOCATOR option can be used to turn this functionality off and remove the device link requirement (it’s Off by default).

**Comment by mclarsen** [comment]
Does umpire need a device link step to be performed by the application using it or does it do itself?

**Comment by mclarsen** [comment]
When compiling statically, I had to add the device link step inside umpire.

**Comment by davidbeckingsale** [comment]
By the application, but it should be done automatically if you are using our CMake targets.

**Comment by mclarsen** [comment]
ok. That makes sense. I don't have a cmake build system, so I will go the patch route. Is it sad that i miss cmake a little?

**Comment by mclarsen** [comment]
I thought about this a bit more. Do you ever compile umpire with cuda statically?

**Pull request closed without merging**
