### PR TITLE
Updated script to obtain version information from tag in git

### PR DESCRIPTION
**Pull request by mcfadden8**

### CODE REVIEW

**Comment by mcfadden8** [comment]
Any comments on this @davidbeckingsale?

**Comment by davidbeckingsale** [comment]
The issue I see is that we create the tag on GitHub, so the new tag won't exist when you want to run this script to create the release tarball (since you will be running it while creating the new release on GitHub)

**Comment by mcfadden8** [comment]
> The issue I see is that we create the tag on GitHub, so the new tag won't exist when you want to run this script to create the release tarball (since you will be running it while creating the new release on GitHub)

Good point.  Hmm.

**Comment by rhornung67** [comment]
FWIW, I don't think there is a way to create a release tarball as part of the release creation/version tagging process on GitHub. Please let me know if you come up with something like that. To me, it would make more sense if GitHub included all submodules when it creates release "assets".

**Comment by mcfadden8** [comment]
As per the notes above, this solution will not work.

**Pull request closed without merging**
