### PR TITLE
adding _hwm replay option for both blocks and free_percentage heuristics

### PR DESCRIPTION
**Pull request by kab163**
The purpose of this PR is to add a _hwm option to replay. I would like to have a .replay or .stats file and be able to use the replay tool to tell me what would happen if I had used a highwatermark option with my pool. For example, replay should now have
```
Options:
  -h,--help                   Print this help message and exit
  -i,--infile TEXT:FILE REQUIRED
                              Input file
  -q,--quiet                  Only errors will be displayed.
  -t,--time-run               Display time information for replay running operations
  -d,--dump                   Dump ULTRA memory usage trace for each Allocator
  -s,--stats                  Track/Display pool allocation size statistics
  --no-demangle               Disable demangling of replay file
  --skip-operations           Skip Umpire Operations during replays
  -r,--recompile              Force recompile replay binary
  -p,--use-pool TEXT          Specify pool to use: List or Quick
  --use-heuristic TEXT        Heuristic: Block, Block_hwm, FreePercentage, or FreePercentage_hwm
  --heuristic-parm INT:INT in [0 - 100]
                              Heuristic parameter to use
```
And I could use `--use-heuristic Block_hwm` to test the Blocks releasable heuristic with a highwatermark tuning on my pool.

### CODE REVIEW

**Comment by kab163** [comment]
@davidbeckingsale @mcfadden8 - I reverted the replay output files back to develop versions since that was not needed

**Comment by mcfadden8** [comment]
Why weren't they needed?  Is there not a replay test for running with the HWM heuristic?  (it has been a while since I last looked at this)

**Comment by kab163** [comment]
> Why weren't they needed? Is there not a replay test for running with the HWM heuristic? (it has been a while since I last looked at this)

See MM chat

**Review by mcfadden8 — APPROVED** [review]
Looks great, thanks @kab163!

**Pull request merged**
