### PR TITLE
Prefix fmt macros to avoid conflicts

### PR DESCRIPTION
**Pull request by adayton1**

### CODE REVIEW

**Comment by YohannDudouit** [comment]
We're also facing this issue in [GEOSX](https://github.com/GEOSX/GEOSX) (If this can motivate this fix to be merged faster).

**Comment by adrienbernede** [comment]
@adayton1 @davidbeckingsale I re-triggered the corona jobs, they were failing independently from this PR.

**Review by mcfadden8 — APPROVED** [review]
This looks good to me.  Thanks!

**Comment by adayton1** [comment]
@davidbeckingsale, any more comments?

**Review by davidbeckingsale — APPROVED** [review]

**Pull request merged**
