### PR TITLE
Make ENABLE_WARNINGS_AS_ERRORS off by default

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by jdahm** [comment]
Can we only make this OFF by default if compiling in Release mode?

**Comment by davidbeckingsale** [comment]
No.

**Comment by mcfadden8** [comment]
@davidbeckingsale, why can't we have warnings as error for develop builds?

**Comment by mcfadden8** [comment]
I see that this got merged.  What was the rush to get this merged?

**Pull request merged**
