### PR TITLE
Fix source documentation link to doxygen

### PR DESCRIPTION
**Pull request by kab163**
Check the docs here: https://umpire.readthedocs.io/en/bugfix-um-959-fix-source-docs-link/

You should see the "Doxygen" sidebar link that goes directly to the Doxgen index.

### CODE REVIEW

**Review by rhornung67 — COMMENTED** [review]
@kab163 this won't work for non-develop versions of the docs, will it? it looks like all doc versions will be pointing at the develop source docs.

**Comment by davidbeckingsale** [comment]
I agree with Rich - this points directly at develop - is there a way to make it work without doing that?

**Comment by rhornung67** [comment]
I'm putzing around with this and trying a few things in the RAJA docs. I think this all started with the "fancy hack" I found on stackoverflow.... https://stackoverflow.com/questions/27979803/external-relative-link-in-sphinx-toctree-directive

All attempts failed....mission aborted. I can't figure out how to get a properly generated relative link in the TOC that appears on any child page.  You might consider removing the link to the source docs from the TOC and only linking to it from your main page....

**Comment by kab163** [comment]
Looks great! Thanks for the fix, David!

**Comment by davidbeckingsale** [comment]
@rhornung67 - this fixes it, let me know if you need help adding it to RAJA. The trick is creating an empty index.rst in the doxygen directory so that Sphinx finds it and generates the links (and an index.html in the build directory). You then overwrite that index.html by running Doxygen _after_ Sphinx has finished.

**Comment by rhornung67** [comment]
I'll take a look and let you know if I need help. Thanks.

**Review by mcfadden8 — APPROVED** [review]

**Pull request merged**
