### PR TITLE
Feature/um 650 add umpire poison memory region checks to quickpool

### PR DESCRIPTION
**Pull request by mcfadden8**

### CODE REVIEW

**Comment by mcfadden8** [comment]
Should be good for final checks now.

**Comment by davidbeckingsale** [comment]
I remember why it's guarded... The `UMPIRE_POISON` macros have to check the platform (adds an if statement), so that's why I made sure it could be disabled. Do you think that really matters?

**Comment by mcfadden8** [comment]
Hmm.

**Comment by mcfadden8** [comment]
Almost there.  I think I have the compilers on bamboo working.

**Comment by mcfadden8** [comment]
Okay @davidbeckingsale , this is ready.

**Pull request merged**
