### PR TITLE
Use cmake_dependent_option with BLT options

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Hey @gzagaris I'm going to merge from here just to make sure our internal CI is passing (I think Rich did the same thing with the RAJA PR)

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by rhornung67** [comment]
Yup. That's why I made the script to pull in branches from forked repos to make PRs that would run all the CI tools.

**Comment by gzagaris** [comment]
Awesome -- thanks @davidbeckingsale!

**Review by mcfadden8 — APPROVED** [review]

**Review by kab163 — APPROVED** [review]
(Note: Following up with ticket for adding UMPIRE prefix to other cmake options too!)

**Pull request merged**
