### PR TITLE
Update BLT to version 0.3.0

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
(previous message is a test for gitlab mirroring)

**Comment by davidbeckingsale** [comment]
@mcfadden8 - can you take a look at this?

**Comment by davidbeckingsale** [comment]
You put them in to fix warnings in one of the compilers on Bamboo I think. I'm going to check everything still passes there before merging.

**Pull request merged**
