### PR TITLE
Allocator size cost benchmark

### PR DESCRIPTION
**Pull request by mcfadden8**

### CODE REVIEW

**Comment by kab163** [comment]
Could you add the output from the benchmark?

**Comment by kab163** [comment]
Also, this may be a dumb question so bear with me, but why are the options Host, Quick, or malloc? Host seems like the resource, HOST, Quick seems like an allocation strategy (Quickpool), and malloc seems like the std function - which all seem like different things, so how can this comparison be done? I feel like I'm missing some context.

**Comment by mcfadden8** [comment]
> Could you add the output from the benchmark?

Here ya go!  (it is also in the Jira ticket)

```
$ srun -N1-1 --exclusive ./bin/allocator_memory_cost_benchmark --help
Benchmark the memory overhead per allocation of an Allocator
Usage: /usr/WS2/martymcf/src/benchmark.umpire/build/./bin/allocator_memory_cost_benchmark [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  -a,--use-allocator TEXT REQUIRED
                              Specify Allocator to use: Host, Quick, or malloc
  -n,--num-allocations UINT:INT in [0 - 100000000] REQUIRED
                              Specify number of allocations to perform
  --no_introspection          Disable introspection
  --show_process_mem_info     Display process memory details
```

```
$ srun -N1-1 --exclusive ./bin/allocator_memory_cost_benchmark -a malloc -n $((64*1024*1024))
67108864 4-byte allocs from malloc uses 2.00 gigabytes of memory, costing 31.00 bytes, and 35.8131 nanoseconds per allocation
```

```
$ srun -N1-1 --exclusive ./bin/allocator_memory_cost_benchmark -a malloc -n $((64*1024*1024)) --show_process_mem_info
67108864 4-byte allocs from malloc
VmExe Total{652.00 kilobytes}, Baseline{652.00 kilobytes}, Cost{0.00 bytes}, or {0.00 bytes}/allocation
VmPTE Total{5.05 megabytes}, Baseline{1.05 megabytes}, Cost{4.00 megabytes}, or {0.00 bytes}/allocation
VmRSS Total{2.50 gigabytes}, Baseline{513.55 megabytes}, Cost{2.00 gigabytes}, or {31.00 bytes}/allocation
VmStk Total{144.00 kilobytes}, Baseline{144.00 kilobytes}, Cost{0.00 bytes}, or {0.00 bytes}/allocation
VmHWM Total{2.50 gigabytes}, Baseline{513.55 megabytes}, Cost{2.00 gigabytes}, or {31.00 bytes}/allocation
VmData Total{2.50 gigabytes}, Baseline{512.28 megabytes}, Cost{2.00 gigabytes}, or {31.00 bytes}/allocation
VmSize Total{2.51 gigabytes}, Baseline{527.07 megabytes}, Cost{2.00 gigabytes}, or {31.00 bytes}/allocation
VmLib Total{3.91 megabytes}, Baseline{3.91 megabytes}, Cost{0.00 bytes}, or {0.00 bytes}/allocation
VmPeak Total{2.51 gigabytes}, Baseline{783.07 megabytes}, Cost{1.75 gigabytes}, or {27.00 bytes}/allocation
Memory Usage HSM Total{2.50 gigabytes}, Baseline{513.55 megabytes}, Cost{2.00 gigabytes}, or {31.00 bytes}/allocation
```

**Comment by mcfadden8** [comment]
> Also, this may be a dumb question so bear with me, but why are the options Host, Quick, or malloc? Host seems like the resource, HOST, Quick seems like an allocation strategy (Quickpool), and malloc seems like the std function - which all seem like different things, so how can this comparison be done? I feel like I'm missing some context.

Good question.  These names are intended to indicate different kinds of allocator where:

"malloc" - use the raw system call (no Umpire)
"Host" - use the Umpire device allocator (no strategies)
"Quick" - use the Umpire QuickPool strategy

I'm happy to change the names if it will help.  Let me know if you have any suggestions.

**Comment by kab163** [comment]
> > Also, this may be a dumb question so bear with me, but why are the options Host, Quick, or malloc? Host seems like the resource, HOST, Quick seems like an allocation strategy (Quickpool), and malloc seems like the std function - which all seem like different things, so how can this comparison be done? I feel like I'm missing some context.
> 
> Good question. These names are intended to indicate different kinds of allocator where:
> 
> "malloc" - use the raw system call (no Umpire) "Host" - use the Umpire device allocator (no strategies) "Quick" - use the Umpire QuickPool strategy
> 
> I'm happy to change the names if it will help. Let me know if you have any suggestions.

Ok, that makes sense. I understand the comparison. The only other question I have is why you name the second one "Host" when we are using the Umpire "device" allocator? I think the other names are fine though. (We have what each allocator name means/is meant to show documented somewhere in the JIRA right? I could see myself forgetting this in a couple months lol) @davidbeckingsale any thoughts?

**Comment by mcfadden8** [comment]
> > > Also, this may be a dumb question so bear with me, but why are the options Host, Quick, or malloc? Host seems like the resource, HOST, Quick seems like an allocation strategy (Quickpool), and malloc seems like the std function - which all seem like different things, so how can this comparison be done? I feel like I'm missing some context.
> > 
> > 
> > Good question. These names are intended to indicate different kinds of allocator where:
> > "malloc" - use the raw system call (no Umpire) "Host" - use the Umpire device allocator (no strategies) "Quick" - use the Umpire QuickPool strategy
> > I'm happy to change the names if it will help. Let me know if you have any suggestions.
> 
> Ok, that makes sense. I understand the comparison. The only other question I have is why you name the second one "Host" when we are using the Umpire "device" allocator? I think the other names are fine though. (We have what each allocator name means/is meant to show documented somewhere in the JIRA right? I could see myself forgetting this in a couple months lol)

The only reason that I steered away from using DEVICE was because this is really intended to be a HOST-only benchmark.  The memory statistics being gathered are all host-centric.  I think we would need a different benchmark for devices.

**Comment by kab163** [comment]
> > > > Also, this may be a dumb question so bear with me, but why are the options Host, Quick, or malloc? Host seems like the resource, HOST, Quick seems like an allocation strategy (Quickpool), and malloc seems like the std function - which all seem like different things, so how can this comparison be done? I feel like I'm missing some context.
> > > 
> > > 
> > > Good question. These names are intended to indicate different kinds of allocator where:
> > > "malloc" - use the raw system call (no Umpire) "Host" - use the Umpire device allocator (no strategies) "Quick" - use the Umpire QuickPool strategy
> > > I'm happy to change the names if it will help. Let me know if you have any suggestions.
> > 
> > 
> > Ok, that makes sense. I understand the comparison. The only other question I have is why you name the second one "Host" when we are using the Umpire "device" allocator? I think the other names are fine though. (We have what each allocator name means/is meant to show documented somewhere in the JIRA right? I could see myself forgetting this in a couple months lol)
> 
> The only reason that I steered away from using DEVICE was because this is really intended to be a HOST-only benchmark. The memory statistics being gathered are all host-centric. I think we would need a different benchmark for devices.

I think that sounds very reasonable. Then the other thing I'm confused about is why "Host" doesn't then just give us a host allocator -- update: I checked this and on line 105, you do grab the HOST resource but you call it "device_allocator". Is there a reason for that?

**Comment by mcfadden8** [comment]
> > > > > Also, this may be a dumb question so bear with me, but why are the options Host, Quick, or malloc? Host seems like the resource, HOST, Quick seems like an allocation strategy (Quickpool), and malloc seems like the std function - which all seem like different things, so how can this comparison be done? I feel like I'm missing some context.
> > > > 
> > > > 
> > > > Good question. These names are intended to indicate different kinds of allocator where:
> > > > "malloc" - use the raw system call (no Umpire) "Host" - use the Umpire device allocator (no strategies) "Quick" - use the Umpire QuickPool strategy
> > > > I'm happy to change the names if it will help. Let me know if you have any suggestions.
> > > 
> > > 
> > > Ok, that makes sense. I understand the comparison. The only other question I have is why you name the second one "Host" when we are using the Umpire "device" allocator? I think the other names are fine though. (We have what each allocator name means/is meant to show documented somewhere in the JIRA right? I could see myself forgetting this in a couple months lol)
> > 
> > 
> > The only reason that I steered away from using DEVICE was because this is really intended to be a HOST-only benchmark. The memory statistics being gathered are all host-centric. I think we would need a different benchmark for devices.
> 
> I think that sounds very reasonable. Then the other thing I'm confused about is why "Host" doesn't then just give us a host allocator -- update: I checked this and on line 105, you do grab the HOST resource but you call it "device_allocator". Is there a reason for that?

Good points.  I fixed the variable naming and I updated the help as follows:
```
$ srun -N1-1 --exclusive ./bin/allocator_memory_cost_benchmark --help
Benchmark the memory overhead per allocation of an Allocator
Usage: /usr/WS2/martymcf/src/benchmark.umpire/build/./bin/allocator_memory_cost_benchmark [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  -a,--use-allocator TEXT REQUIRED
                              Specify Allocator to use: 'Host', 'Quick', or 'malloc'.
                              When 'malloc' is specified, use the raw system call (no Umpire).
                              When 'Host' is specified, use HOST Umpire resource allocator.
                              When 'Quick' is specified, use the Umpire Quickpool allocator.

  -n,--num-allocations UINT:INT in [0 - 100000000] REQUIRED
                              Specify number of allocations to perform
  --no_introspection          Disable introspection
  --show_process_mem_info     Display process memory details
```

**Comment by kab163** [comment]
Thanks Marty!

**Comment by mcfadden8** [comment]
> Thanks Marty!

Does this mean you approve?  Care to click the button? :-)

**Comment by mcfadden8** [comment]
@davidbeckingsale, this one is ready too

**Review by davidbeckingsale — APPROVED** [review]

**Pull request merged**
