### PR TITLE
Restructure installed CMake configs & add tests

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
CC @trws @rhornung67  - I think we can use this pattern in RAJA

**Review by mcfadden8 — DISMISSED** [review]
This is nice.

**Comment by rhornung67** [comment]
> CC @trws @rhornung67 - I think we can use this pattern in RAJA

@davidbeckingsale are you referring to the BLT tpl stuff specifically, or something else?

**Comment by davidbeckingsale** [comment]
> > CC @trws @rhornung67 - I think we can use this pattern in RAJA
> 
> @davidbeckingsale are you referring to the BLT tpl stuff specifically, or something else?

Yes, importing the BLT targets first prior to camp/RAJA, and also caching the camp_DIR so that we can try that if one is used. Finally, I think we can incorporate a test of the installed config. So I guess we could use everything in this PR 😄

**Comment by rhornung67** [comment]
@davidbeckingsale do you have time to put up a RAJA PR with this?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale do you have time to put up a RAJA PR with this?

Yup, just let me work out the kinks here first.

**Review by mcfadden8 — APPROVED** [review]

**Pull request merged**
