### PR TITLE
Bugfix/um 701 fix enable mpi on builds of umpire

### PR DESCRIPTION
**Pull request by mcfadden8**
I believe that this bug was likely caused by our style code reorganizing header files.  It is a legitmate problem because MPI.hpp was incorrectly not including util/config.hpp and it needed it.

### CODE REVIEW

**Comment by mcfadden8** [comment]
LGTM

**Review by davidbeckingsale — APPROVED** [review]
Can you please do a 4.0.1 release? And I don't think we should use pragma once yet...

**Comment by davidbeckingsale** [comment]
LGTM.

**Comment by mcfadden8** [comment]
LGTM

**Comment by mcfadden8** [comment]
LGTM

**Comment by mcfadden8** [comment]
LGTM

**Comment by mcfadden8** [comment]
LGTM

**Comment by mcfadden8** [comment]
Closing this PR as it needs more work.  Note, I will also be renaming the branch.  Stay tuned.

**Pull request closed without merging**
