### PR TITLE
Disable multi-project job for now

### PR DESCRIPTION
**Pull request by davidbeckingsale**
Temporarily disable multi-project GitLab CI job (until CHAI is fixed).

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
Please ignore the CHANGELOG test - I'm not going to edit that for this change.

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
@mcfadden8 @kab163 thoughts?

**Review by mcfadden8 — APPROVED** [review]
This is strange.  I reviewed/approved this yesterday. No idea why this didn't go through.

**Review by kab163 — APPROVED** [review]
Yea, I could have sworn I got emails about it being approved and actually already merged lol - I think git is acting up or something (either that, or I'm going crazy!)

**Pull request merged**
