### PR TITLE
Add CI documentation to developer guide

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Review by adrienbernede — APPROVED** [review]
This looks OK to me. Any request that has to be addressed in here?

**Comment by davidbeckingsale** [comment]
LGTM

**Review by mcfadden8 — APPROVED** [review]

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
I missed the opportunity to merge this. As a consequence, changes made by @kab163 where conflicting.
Some of those where added directly to radiuss-ci shared documentation. Umpire specific stuff was moved to the uberenv.rst.

**Comment by adrienbernede** [comment]
LGTM

**Pull request merged**
