### PR TITLE
Add sub-pipeline status report

### PR DESCRIPTION
**Pull request by adrienbernede**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@adrienbernede do your current PRs need to be merged in a specific order?

**Comment by adrienbernede** [comment]
@davidbeckingsale things should be looked at from the Radiuss-Shared-CI perspective. I think we should always reference a tag in Radiuss-Shared-CI.

E.g., this branch should only be merged after we merge the related branch in Radiuss-Shared-CI and update the ref here.

I suggest the following sequence:

1. merge https://github.com/LLNL/Umpire/pull/764

2. merge https://github.com/LLNL/radiuss-shared-ci/pull/3

3. merge https://github.com/LLNL/radiuss-shared-ci/pull/6

4. create a radiuss-shared-ci release tag (covers both change)
    typically 2022-08-1, not that strictly speaking, there is a breaking change, so a minor increase in not ideal, but at this scale....

5. adapt and merge https://github.com/LLNL/Umpire/pull/769

6. the present PR will be obsolete after 5.

**Comment by adrienbernede** [comment]
If you agree, I’ll proceed. I am waiting for #769 to report. I can’t connect to LC Gitlab at the moment which slows me down a bit.

**Comment by adrienbernede** [comment]
@davidbeckingsale "1" is ready to go. I did "2" and "3". I am ready to do "4" if we agree that "2022-08-1" is an OK name for that release.

**Comment by rhornung67** [comment]
@davidbeckingsale is this for the coordinated release?  RAJA release will happen in mid-late September. There is way too much going on right now to push it out in August.

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale "1" is ready to go. I did "2" and "3". I am ready to do "4" if we agree that "2022-08-1" is an OK name for that release.

I agree on the name for the shared CI release tag, and I just merged #764

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale is this for the coordinated release? RAJA release will happen in mid-late September. There is way too much going on right now to push it out in August.

Not specifically, but I think it would be good to get the CI squared away so that the `main` branches will have all this stuff. September timeframe should be fine.

**Comment by adrienbernede** [comment]
Closing in favor of #769

**Comment by adrienbernede** [comment]
Closing in favor of #769

**Pull request closed without merging**
