### PR TITLE
Allow resource release as soon as possible

### PR DESCRIPTION
**Pull request by adrienbernede**
This is a simple improvement or bugfix for Gitlab CI.

With this change, resources allocated on quartz can be released as soon as possible, preventing waste if lassen jobs takes too much time for example.

This is possible thanks to the "needs" key word, already introduced for build and test jobs. This time, the quartz job releasing resources will be triggered as soon as every quartz test job is complete.

Note:
This works even in the test jobs ended in "allowed failure", "skipped" or "failure" state.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@adrienbernede - do you know why this is failing the GitLab CI?

**Comment by adrienbernede** [comment]
My bet is I happened to push on a day lassen wasn’t available.
I re-ran it and it now passes (should be on the same link).

**Comment by adrienbernede** [comment]
Good news, the status has been updated on GitHub as well!
I didn’t know we could do that!

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
(Above comment it a test for CI)

**Comment by adrienbernede** [comment]
Merge me, please... ? :)
@davidbeckingsale

**Comment by adrienbernede** [comment]
Thanks!

**Pull request merged**
