### PR TITLE
python -> python3 binary name

### PR DESCRIPTION
**Pull request by adrienbernede**
Python binary has been removed in favor of explicit python3 or python2.

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Review by davidbeckingsale — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
Thanks for the quick fix @adrienbernede !

**Comment by adrienbernede** [comment]
@davidbeckingsale  I had to clean the cache.
That’s because our cache key "venv" is the same for all branches. So in the rare event of a change in the python env, the cache has to be removed in order for the environment to be updated.
The alternative is to force one cache per branch, but then we lose the benefit of caching because we usually run Gitlab CI only once or twice per branch. Still, that’s more robust.
What do you think?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale I had to clean the cache.
> That’s because our cache key "venv" is the same for all branches. So in the rare event of a change in the python env, the cache has to be removed in order for the environment to be updated.
> The alternative is to force one cache per branch, but then we lose the benefit of caching because we usually run Gitlab CI only once or twice per branch. Still, that’s more robust.
> What do you think?

I think using the same cache is a good idea. If we have to manually clean the cache occasionally I don't think that's a problem.

**Comment by adrienbernede** [comment]
LGTM

**Pull request merged**
