### PR TITLE
Fixes for multi-device support

### PR DESCRIPTION
**Pull request by davidbeckingsale**
- Check whether there is > 1 device
- Fix setup of sycl per-device queues

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
LGTM.

**Review by mcfadden8 — APPROVED** [review]
I'm not 100% certain about the SYCL changes since I don't know how they work, but the changes in ResourceManager for the DEVICE support looks great!  Thanks

**Review by kab163 — APPROVED** [review]
Looks good to me!

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by anis-ladram** [comment]
@davidbeckingsale just so you know, regarding this PR, for now the compute-sanitizer only handles allocations for devices where cudaDeviceEnablePeerAccess has been called before. I didn't mention this limitation at first considering it wouldn't impact you, but it might be useful to mention it now. I will get rid of this limitation ASAP.

**Pull request merged**
