### PR TITLE
Add PID to filenames

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@mcfadden8 - I think adding the PID might make the second uid in the filename redundant. What do you think?

**Comment by davidbeckingsale** [comment]
I think the filenames always need to keep the same format. Easier for sorting, tools to process, etc.

**Comment by mcfadden8** [comment]
Okay, then I would keep the uid even though it will be 0 most of the time.  There is an ever-so-slight chance that a PID might collide.

**Comment by davidbeckingsale** [comment]
@mcfadden8 - I'll update the documentation.

**Pull request merged**
