### PR TITLE
Plot allocator traces with a python script

### PR DESCRIPTION
**Pull request by jdahm**

### CODE REVIEW

**Comment by jdahm** [comment]
@davidbeckingsale now that you've had a chance to try the script, is there anything else it needs before merging?

**Comment by davidbeckingsale** [comment]
Why is BLT updated here?

**Comment by jdahm** [comment]
@davidbeckingsale because I failed at merging :)

**Comment by davidbeckingsale** [comment]
Can you get rid of the BLT changes please?

**Pull request merged**
