### PR TITLE
Task/um 804 size limiter example

### PR DESCRIPTION
**Pull request by kab163**

### CODE REVIEW

**Comment by kab163** [comment]
LGTM

**Review by davidbeckingsale — COMMENTED** [review]
The formatting of those braces is a bit weird 😄

**Comment by kab163** [comment]
> The formatting of those braces is a bit weird 😄

Don't be hating on my braces

**Comment by kab163** [comment]
LGTM

**Review by davidbeckingsale — APPROVED** [review]

**Pull request merged**
