### PR TITLE
Convert CTest output to JUnit for GitLab

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Review by mcfadden8 — COMMENTED** [review]
Looks great @davidbeckingsale!  Please update Changelog.

**Review by mcfadden8 — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Pull request merged**
