### PR TITLE
Point at develop TPLs in CI

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Review by mcfadden8 — APPROVED** [review]

**Comment by kab163** [comment]
Why do we only have a blt@develop option? Why not a camp option?

**Comment by davidbeckingsale** [comment]
> Why do we only have a blt@develop option? Why not a camp option?

camp doesn't have a develop branch. Numbered releases are tagged, and `master` is the latest development.

**Comment by kab163** [comment]
> > Why do we only have a blt@develop option? Why not a camp option?
> 
> camp doesn't have a develop branch. Numbered releases are tagged, and `master` is the latest development.

Makes sense. Also, is there a reason for changing hip to rocm?

**Comment by davidbeckingsale** [comment]
> > > Why do we only have a blt@develop option? Why not a camp option?
> > 
> > 
> > camp doesn't have a develop branch. Numbered releases are tagged, and `master` is the latest development.
> 
> Makes sense. Also, is there a reason for changing hip to rocm?

Using Spack's ROCmPackage.

**Review by kab163 — APPROVED** [review]

**Pull request merged**
