### PR TITLE
Add UMPIRE_ prefix to CMake variables

### PR DESCRIPTION
**Pull request by kab163**
Trying to redo this process, if it works, will replace the other PR that's already open

### CODE REVIEW

**Comment by kab163** [comment]
(Although I think the idea is to hold off on this PR for now and wait for Rich and others to decide how the cmake_dependent_options will affect their codes before this would be merged... but just putting this out there)

**Comment by rhornung67** [comment]
I think the cmake dep options should be fine. We do something similar in RAJA and Axom already.

**Comment by davidbeckingsale** [comment]
@kab163 can you get this up to date with develop so we can get it merged? Everything is looking good.

**Comment by kab163** [comment]
> @kab163 can you get this up to date with develop so we can get it merged? Everything is looking good.

@davidbeckingsale - everything should be up-to-date and ready to go!

**Review by davidbeckingsale — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
> > @kab163 can you get this up to date with develop so we can get it merged? Everything is looking good.
> 
> @davidbeckingsale - everything should be up-to-date and ready to go!

Are you sure? 😉

**Pull request merged**
